version: "2"
services:
  app:
    env_file: .env
    container_name: express
    restart: always
    build: 
      context: ./server
      args:
        PORT: ${PORT} 
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo
  mongo:
    env_file: .env
    container_name: mongo
    image: mongo
    ports:
      - "${DBPORT}:${DBPORT}"
    volumes:
      - ExpressWithAuth:/data/db
volumes:
  ExpressWithAuth: